### ISSUE TITLE
不能发送私信

### ISSUE THREAD

**Issue by Atleisure** [linyuchen/LiteLoaderQQNT-OneBotApi#1]
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/72290399/db6e74af-fb0e-47c6-a6c9-ea530ef4f32a)
这样仍然不能发送

**Comment by Atleisure** [comment]
按照群消息api可以发送群消息

**Comment by linyuchen** [comment]
> ![512a3d68e6fb793086957b15e1d51924](https://private-user-images.githubusercontent.com/72290399/289004295-d71fadbc-7e40-4e1d-b3e9-3f4b9526170d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjM1NTcsIm5iZiI6MTcwMjAyMzI1NywicGF0aCI6Ii83MjI5MDM5OS8yODkwMDQyOTUtZDcxZmFkYmMtN2U0MC00ZTFkLWIzZTktM2Y0Yjk1MjYxNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYzQ5NzgzOGU0M2JlMmY4YWFhYTA2NTBlYTQ4Y2EzOWI2MDc5NDI0MGJlZDBmZmI2ODM5OTA5ODc2MmZmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AkoXjlYLJP_BC3xZol4sMZQSpcMrx588r6lv0Su175k) 这个还是不行

可能私聊的api有点问题，我这边测试也是发不出去，晚点我修复看看
