### ISSUE TITLE
能否增加除了 Onebot 协议外的直接 message 上报？

### ISSUE THREAD

**Issue by MizurenNanako** [linyuchen/LiteLoaderQQNT-OneBotApi#14]
比如在 render `handleNewMessage` 中直接将所有 message 进行 JSON 序列化后发给另一个指定的上报服务器，作为测试以及在onebotapi支持不完全的时候的替代来使用？

**Comment by linyuchen** [comment]
直接在上报消息加个`raw`之类字段带上原始message就行了，现在插件是支持多个上报地址的，没有单独搞一个来处理，如果有时间的话你可以尝试改一下提个PR，_(:з」∠)_

**Comment by linyuchen** [comment]
[v2.2.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已新增debug模式可上报原始消息

**Comment by MizurenNanako** [comment]
辛苦了
