### ISSUE TITLE
无法正确连接nonebot

### ISSUE THREAD

**Issue by yhzcake** [linyuchen/LiteLoaderQQNT-OneBotApi#15]
qq版本: 9.9.7-20811 (64位)
llapi版本:1.3.1
llonebot版本:2.1.1

**Comment by linyuchen** [comment]
是不是勾选了自动登录
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/10002169/b58204d2-cbc2-4b97-ae51-68efe6cdf914)
去掉试一下，如果没有勾选，启动QQ的时候多等几秒再点那个登录按钮试试

**Comment by yhzcake** [comment]
一直没勾过,等了
还是不行
跟其他插件会有冲突吗,或者账号消息太多了

**Comment by linyuchen** [comment]
> 一直没勾过,等了 还是不行 跟其他插件会有冲突吗,或者账号消息太多了

你是多开QQ测试的吗，试试只登陆一个账号，用手机发消息测一下看看

**Comment by linyuchen** [comment]
我这边用和你相同版本的QQ复现不了你的情况

安装[devtools](https://github.com/mo-jinran/chii-devtools)插件，启动QQ后按F12，看一下console的输出

**Comment by linyuchen** [comment]
试试[v2.1.2](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases/)

**Comment by yhzcake** [comment]
没,只开了一个qq

**Comment by yhzcake** [comment]
更新到2.1.2好了,多谢

**Comment by yhzcake** [comment]
话说能不能在设置界面加个开关?我同一台电脑上多用户后台开个qq挂bot,但是主用户的qq不想被占资源,所以想一个开着一个关着,但是用的是同一套liteloader的配置,互相冲突...

**Comment by linyuchen** [comment]
> 话说能不能在设置界面加个开关?我同一台电脑上多用户后台开个qq挂bot,但是主用户的qq不想被占资源,所以想一个开着一个关着,但是用的是同一套liteloader的配置,互相冲突...

你应该把安装好的QQ目录复制一份出来，然后走一遍liteloader安装程序，liteloader安装位置不要和主QQ一致，这样LiteLoader配置就不会冲突了，另外插件的开关在LiteLoader已经提供了
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/10002169/2b0da0ed-a43f-4950-9a37-ab117e8405c3)

**Comment by yhzcake** [comment]
只能这么麻烦单独复制一份吗...磁盘状态堪忧

**Comment by linyuchen** [comment]
> 只能这么麻烦单独复制一份吗...磁盘状态堪忧

这是目前最优解，除非Liteloader实现账号分开配置，不然你的bot也有加载你的其他插件，占用资源更多，bot只需要一个bot插件就够了

**Comment by yhzcake** [comment]
行吧..那就这样吧,多谢
