### ISSUE TITLE
撤回对话的接口参数message_id类型错误

### ISSUE THREAD

**Issue by LoseAustyn** [linyuchen/LiteLoaderQQNT-OneBotApi#17]
发现版本：v2.1.1

![图片](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/48990657/f8fd85a1-6be9-4f1b-9349-4aa4ddbd53db)

根据onebot11文档，图片箭头所指的message_id参数应该为int类型，

但是接口只在message_id为str类型时能够正常使用

**Comment by linyuchen** [comment]
这有个非常蛋疼的问题，ntqq的message_id是个非常大的数，原始数据就是用string保存的，如果传过来的是int类型，js会精度丢失。
如post过来的是7405472097755331634，结果js拿到的就是7405472097755332000，有什么好的解决方案吗

**Comment by LoseAustyn** [comment]
我简单查了下，或许可以使用BigNumber.js库？

[https://cdn.jsdelivr.net/npm/bignumber.js/bignumber.min.js](url)

```js
const BigNumber = require('bignumber.js');

// 假设客户端发送的 JSON 数据为 jsonData
const jsonData = {"message_id":7405472097755331634};

// 处理 JSON 数据中的整数
Object.keys(jsonData).forEach(key => {
    const value = jsonData[key];
    if (typeof value === 'number') {
        // 使用 BigNumber 将数值转换为字符串形式
        jsonData[key] = new BigNumber(value).toString();
    }
});

// jsonData 中的整数已经被转换为字符串形式，确保了精度不丢失

// 服务器端继续处理 jsonData

```

我主要是写python的，js没写过多少，不知道行不行

**Comment by linyuchen** [comment]
[v2.2.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)fixed
