### ISSUE TITLE
对新版QQ下发送消息失败的问题

### ISSUE THREAD

**Issue by MarisaDA-ZE** [linyuchen/LiteLoaderQQNT-OneBotApi#23]
版本说明：
QQNT：9.9.7-21357 (64位)
LiteLoader：1.0.3
Chromium：120.0.6099.56
Electron：28.0.0
Node.js：18.18.2
LLAPI：1.3.1
操作：
`POST http://192.168.10.101:3000/send_msg`
发送数据：
`{
    "message_type": "group",
    "group_id": 701339984,
    "message": [
        {
            "type": "text",
            "data": {
                "text": "哈喽！"
            }
        }
    ],
    "auto_escape": false
}`
响应数据：
`{
    "retcode": 0,
    "status": 0,
    "data": {},
    "message": "发送成功"
}`
消息内容并没有发出，只是一直像这样转圈
![1AEFA10127522ED0AF430E96AB79DE4E](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/86925192/6567b2c4-3b03-437d-9d86-73daf6efb6fe)
一段时间后显示红色感叹号（发送失败）
日志信息：
`2024/2/4 17:39:48 Fervent Tempo Δ(<botQQ>):"selfInfo {\"uid\":\"<myUID>\",\"qid\":\"\",\"uin\":\"<botQQ>\",\"avatarUrl\":\"\",\"nickName\":\"Fervent Tempo Δ\",\"bio\":\"叮！变成星星吧！\",\"sex\":\"female\",\"raw\":{\"uid\":\"<myUID>\",\"qid\":\"\",\"uin\":\"<botQQ>\",\"nick\":\"Fervent Tempo Δ\",\"remark\":\"\",\"longNick\":\"叮！变成星星吧！\",\"avatarUrl\":\"\",\"birthday_year\":2020,\"birthday_month\":6,\"birthday_day\":1,\"sex\":2,\"topTime\":\"0\",\"isBlock\":false,\"isMsgDisturb\":false,\"isSpecialCareOpen\":false,\"isSpecialCareZone\":false,\"ringId\":\"0\",\"status\":0,\"qidianMasterFlag\":0,\"qidianCrewFlag\":0,\"qidianCrewFlag2\":0,\"extStatus\":0,\"categoryId\":0,\"onlyChat\":false,\"qzoneNotWatch\":false,\"qzoneNotWatched\":false,\"vipFlag\":false,\"yearVipFlag\":false,\"svipFlag\":false,\"vipLevel\":1,\"isZPlanCoupleOpen\":false,\"zplanCoupleSceneId\":0,\"teenagerFlag\":0,\"studyFlag\":0}}"
2024/2/4 17:39:48 Fervent Tempo Δ(<botQQ>):"llonebot loaded"
2024/2/4 17:39:48 Fervent Tempo Δ(<botQQ>):"llonebot render start"
2024/2/4 17:39:48 Fervent Tempo Δ(<botQQ>):"发送消息API已注册"
2024/2/4 17:39:49 Fervent Tempo Δ(<botQQ>):"llonebot render onLoad"
2024/2/4 17:39:50 Fervent Tempo Δ(<botQQ>):"全部群成员获取完毕"
2024/2/4 17:39:52 Fervent Tempo Δ(<botQQ>):"llonebot render onLoad"
2024/2/4 17:40:31 Fervent Tempo Δ(<botQQ>):"setting window created"
2024/2/4 17:40:37 Fervent Tempo Δ(<botQQ>):"llonebot render onLoad"
2024/2/4 17:40:52 Fervent Tempo Δ(<botQQ>):"API receive post:{\"message_type\":\"private\",\"user_id\":<myQQ>,\"message\":[{\"type\":\"text\",\"data\":{\"text\":\"你好！\"}}],\"auto_escape\":false,\"action\":\"send_private_msg\"}"
2024/2/4 17:41:22 Fervent Tempo Δ(<botQQ>):"API receive post:{\"group_id\":<groupID>,\"message_type\":\"group\",\"message\":[{\"data\":{\"text\":\"帮助菜单\\n============\\n@我 <命令><参数>即可使用。\\n-发骚话（文本）：@我 来点骚话\\n-发骚话（语音）：@我 来点语音骚话\\n-复读机（语音）：@我 复读：<内容>\\n-复读机（文本）：@我 复读文本：<内容>\\n-随机图片：@我 来点二次元\\n-开空调：@我 开空调\\n-闭空调：@我 关空调\\n-设置温度：@我 设置温度<温度>\\n-查询温度：@我 查询温度\\n-帮助：@我 帮助\\n-帮助：@我 help\\n============\"},\"type\":\"text\"}],\"action\":\"send_group_msg\"}"
2024/2/4 17:41:24 Fervent Tempo Δ(<botQQ>):"新消息事件上传成功: http://192.168.10.101:8888/ {\"self\":{\"platform\":\"qq\",\"user_id\":\"<botQQ>\"},\"self_id\":\"<botQQ>\",\"time\":1707039682,\"type\":\"message\",\"post_type\":\"message\",\"message_type\":\"group\",\"detail_type\":\"group\",\"message_id\":\"7331679609204350391\",\"sub_type\":\"group\",\"message\":[{\"data\":{\"mention\":\"<botQQ>\",\"qq\":\"<botQQ>\"},\"type\":\"at\"},{\"data\":{\"text\":\" 帮助\"},\"type\":\"text\"}],\"raw_message\":\"\",\"font\":14,\"group_id\":\"<groupID>\",\"user_id\":\"<myQQ>\",\"sender\":{\"user_id\":\"<myQQ>\",\"nickname\":\"<myNickName>\",\"card\":\"万号之主\",\"role\":\"owner\"}}"
2024/2/4 17:43:16 Fervent Tempo Δ(<botQQ>):"API receive post:{\"group_id\":<groupID>,\"message_type\":\"group\",\"message\":[{\"data\":{\"text\":\"帮助菜单\\n============\\n@我 <命令><参数>即可使用。\\n-发骚话（文本）：@我 来点骚话\\n-发骚话（语音）：@我 来点语音骚话\\n-复读机（语音）：@我 复读：<内容>\\n-复读机（文本）：@我 复读文本：<内容>\\n-随机图片：@我 来点二次元\\n-开空调：@我 开空调\\n-闭空调：@我 关空调\\n-设置温度：@我 设置温度<温度>\\n-查询温度：@我 查询温度\\n-帮助：@我 帮助\\n-帮助：@我 help\\n============\"},\"type\":\"text\"}],\"action\":\"send_group_msg\"}"
2024/2/4 17:43:18 Fervent Tempo Δ(<botQQ>):"新消息事件上传成功: http://192.168.10.101:8888/ {\"self\":{\"platform\":\"qq\",\"user_id\":\"<botQQ>\"},\"self_id\":\"<botQQ>\",\"time\":1707039795,\"type\":\"message\",\"post_type\":\"message\",\"message_type\":\"group\",\"detail_type\":\"group\",\"message_id\":\"7331680089068021932\",\"sub_type\":\"group\",\"message\":[{\"data\":{\"mention\":\"<botQQ>\",\"qq\":\"<botQQ>\"},\"type\":\"at\"},{\"data\":{\"text\":\" 帮助\"},\"type\":\"text\"}],\"raw_message\":\"\",\"font\":14,\"group_id\":\"<groupID>\",\"user_id\":\"<myQQ>\",\"sender\":{\"user_id\":\"<myQQ>\",\"nickname\":\"<myNickName>\",\"card\":\"万号之主\",\"role\":\"owner\"}}"
2024/2/4 17:45:02 Fervent Tempo Δ(<botQQ>):"API receive post:{\"message_type\":\"group\",\"group_id\":<groupID>,\"message\":[{\"type\":\"text\",\"data\":{\"text\":\"哈喽！\"}}],\"auto_escape\":true,\"action\":\"send_group_msg\"}"
2024/2/4 17:45:54 Fervent Tempo Δ(<botQQ>):"setting window created"
2024/2/4 17:46:01 Fervent Tempo Δ(<botQQ>):"llonebot render onLoad"
2024/2/4 17:47:40 Fervent Tempo Δ(<botQQ>):"API receive post:{\"message_type\":\"group\",\"group_id\":<groupID>,\"message\":[{\"type\":\"text\",\"data\":{\"text\":\"哈喽！\"}}],\"auto_escape\":false,\"action\":\"send_group_msg\"}"
2024/2/4 17:49:07 Fervent Tempo Δ(<botQQ>):"setting window created"
2024/2/4 17:49:14 Fervent Tempo Δ(<botQQ>):"llonebot render onLoad"
2024/2/4 17:49:19 Fervent Tempo Δ(<botQQ>):"llonebot render onLoad"
2024/2/4 17:50:42 Fervent Tempo Δ(<botQQ>):"setting window created"
2024/2/4 17:50:49 Fervent Tempo Δ(<botQQ>):"llonebot render onLoad"
2024/2/4 17:53:43 Fervent Tempo Δ(<botQQ>):"llonebot render onLoad"
`

**Comment by linyuchen** [comment]
QQ是全新安装的吗，手动发能发出去吗，尝试用别的账号试试，我这边无法复现你的你的情况。

贴日志的时候格式化一下，你这日志挤成一坨没法阅读

**Comment by MarisaDA-ZE** [comment]
> QQ是全新安装的吗，手动发能发出去吗，尝试用别的账号试试，我这边无法复现你的情况。
> 
> 贴日志的时候格式化一下，你这日志挤成一坨没法阅读

日志的事情不好意思。
QQ是从官方那下的最新版，我把原来的9.9.2卸了（腾讯的那个文件夹都删了），然后使用一键安装工具：[https://github.com/Mzdyl/LiteLoaderQQNT_Install/](url) 的安装的LiteLoaderQQNT。
然后从插件商城中安装了1.3.1版本的LLAPI：[https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-LLAPI](url)。
最后将[https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases/download/v2.4.0/LLOneBot.zip](url)解压到plugin文件夹。

可以发送私聊消息（文字、图片可以，语音消息能发送但是没声音）；
群聊消息文本、图片、语音都不能发送：文本是一直转圈，一段时间后超时发送失败，语音图片则是直接发送失败（出现红色感叹号）。

这是我重新装完QQ和机器人后产生的日志。我将\"替换为了"。
`
2024/2/4 20:18:51 Fervent Tempo Δ(<机器人QQ>):"llonebot render onLoad"
# 👇私聊消息
2024/2/4 20:19:32 Fervent Tempo Δ(<机器人QQ>):
"API receive post: {
    "message_type":"private",
    "user_id":<用户QQ>,
    "message":[{
        "type":"text",
        "data":{"text":"你好！"}
        }],
    "auto_escape":false,
    "action":"send_private_msg"
}"

# 👇群聊纯文字
2024/2/4 20:19:51 Fervent Tempo Δ(<机器人QQ>):"API receive post:{
    "message_type":"group",
    "group_id":<群号>,
    "message":[{
        "type":"text",
        "data":{"text":"123"}
    }],
    "auto_escape":true,
    "action":"send_group_msg"
}"

# 👇群聊语音
2024/2/4 20:21:45 Fervent Tempo Δ(<机器人QQ>):"API receive post:{
    "message_type":"group",
    "group_id":<群号>,
    "message":[{
        "type":"record",
        "data":{
            "file":"http://192.168.10.101:8021/audio.mp3"
            }
        }],
    "auto_escape":true,
    "action":"send_group_msg"
}"`

使用Apifox调用接口后返回值也是正常的。
`{
    "retcode": 0,
    "status": 0,
    "data": {},
    "message": "发送成功"
}`
或许我应该把QQ降低下版本？

**Comment by MarisaDA-ZE** [comment]
日志文件👇
[llonebot-2024-2-4.log](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/files/14156811/llonebot-2024-2-4.log)

**Comment by linyuchen** [comment]
装我的版本的LLAPI，链接在[README.md](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi)

另外语音消息不能直接发MP3，要silk编码的

**Comment by MarisaDA-ZE** [comment]
中午更新LLAPI版本为1.3.1.1后解决了，目前没有bug
