### ISSUE TITLE
preload.ts sendSendMsgResult 安全问题 

### ISSUE THREAD

**Issue by PurpleNoon** [linyuchen/LiteLoaderQQNT-OneBotApi#27]
如图所示，`preload.ts` 的 `sendSendMsgResult` 可被渲染端调用执行来发送任意的消息
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/fb97663f-234d-4e38-b862-b2d83fcc818f)

安全提示来源：electron 文档进程间通信中提到的安全警告
[2. 通过预加载脚本暴露 ipcRenderer.send](https://www.electronjs.org/zh/docs/latest/tutorial/ipc#2-%E9%80%9A%E8%BF%87%E9%A2%84%E5%8A%A0%E8%BD%BD%E8%84%9A%E6%9C%AC%E6%9A%B4%E9%9C%B2-ipcrenderersend)
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/5b323dc3-c84b-4de6-ac12-4f48fde3d61b)

或许可以采用以下这种方式来规避这个问题？（只是个人建议）
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/eaa7ddc1-c33b-49ab-8cdf-c59a6d54f4f8)
图中红框部分代码：
`MessageGroup.ts`
```typescript
const msg = await sendIPCMsgAsync<MessageElement, Data>(
    CHANNEL_HANDLE_SINGLE_MESSAGE,
    CHANNEL_BACK_SINGLE_MESSAGE,
    oriMessage
)
```
`IPCSend.ts`
```typescript
export interface SendIPCMsgSession<T> {
    id: string
    data: T
}

export function sendIPCMsgAsync<T, V>(
    channelTo: string,
    channelBack: string,
    data: T
) {
    return new Promise<V>((resolve) => {
        const onceSessionId = `${channelTo}____${uuid4()}`
        const handler = (event: any, result: SendIPCMsgSession<V>) => {
            if (result.id === onceSessionId) {
                resolve(result.data)
                ipcMain.off(channelBack, handler)
                return
            }
        }
        ipcMain.on(channelBack, handler)
        sendIPCMsg(channelTo, {
            id: onceSessionId,
            data,
        })
    })
}
```
`preload.ts`
```typescript
// 感觉 sendSendMsgResult 的实现不安全，因此更改了实现方式
handleSingleMessage: (callback: (session: SendIPCMsgSession<MessageElement>) => void) => {
    ipcRenderer.on(
        CHANNEL_HANDLE_SINGLE_MESSAGE, 
        (_event, value) => callback(value)
    )
},
backSingleMessage: <T>(data: T) => {
    ipcRenderer.send(
        CHANNEL_BACK_SINGLE_MESSAGE, 
        data
    )
},
```

**Comment by linyuchen** [comment]
感谢提醒，可以提个PR，现在在逐步脱离LLAPI，以后不会在renderer进行NTQQ API的相关操作了

**Comment by PurpleNoon** [comment]
唔，明天我看看怎么提 pr，提到 main 还是 dev？看你最近的提交好像没提到 dev 上

**Comment by linyuchen** [comment]
> 唔，明天我看看怎么提 pr，提到 main 还是 dev？看你最近的提交好像没提到 dev 上

到dev吧，现在dev已经和main同步
