### ISSUE TITLE
发送群消息提示code:200，但实际消息并没有发送出去

### ISSUE THREAD

**Issue by 544985365** [linyuchen/LiteLoaderQQNT-OneBotApi#30]
刚开始使用可以发送几条，之后发送code200,但是并没有发送出去，切换qq账号后，会把之前没有发送出去的消息一并发送出去，这是qq的限制吗？好友消息并没有这种问题

**Comment by linyuchen** [comment]
这是不正常的，我需要更多的信息才知道是什么问题导致的

QQ版本:

LLAPI版本:

LLOnebot版本:

你的LLOnebot安装步骤:

调用API的方式(使用的应用端, 如NoneBot、koishi):

**Comment by 544985365** [comment]
我更新了一下LLAPI和LLOnebot可以发送了，之前message可以直接传文本，新版本需要传message对象数组，搞了半天才明白，感谢
