### ISSUE TITLE
不会接收消息通过API, 希望能帮帮孩子qwq

### ISSUE THREAD

**Issue by TonyLiangP2010405** [linyuchen/LiteLoaderQQNT-OneBotApi#33]
QQ版本：9

LLAPI版本：最新

LLOneBot版本：最新

调用LLoneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：python直接http请求

您安装LLOneBot的步骤：

BUG描述：那个弱弱的问一句有没有消息上报的例子, 我只能通过调API发消息, 不会接收消息, 如果有的话十分感谢qwq

复现步骤：

**Comment by PurpleNoon** [comment]
这是我复制来的，看看能不能帮到你
### 上报事件
POST http://127.0.0.1:5000/onebot/v11/
Content-Type: application/json
x-self-id: 2435658320

{
    "self": {
        "platform": "qq",
        "user_id": "2435658320"
    },
    "self_id": "2435658320",
    "time": 0,
    "type": "message",
    "post_type": "message",
    "message_type": "group",
    "detail_type": "group",
    "message_id": "7327911062756138927",
    "sub_type": "",
    "message": [
        {
            "data": {
                "text": "/帮助"
            },
            "type": "text"
        }
    ],
    "raw_message": "",
    "font": 14,
    "group_id": "687454506",
    "user_id": "346014945",
    "sender": {
        "user_id": "346014945",
        "nickname": "xxxxxxx",
        "card": "",
        "role": "owner"
    }
}

**Comment by TonyLiangP2010405** [comment]
十分感谢,不过我感觉好像是我自己的问题, 我以前没碰过onebot好像和我之前用的类别不太一样, 之前用的有receive message的单独API然后调用那个API就能接收消息,这个好像没有,我也不知道我理解的对不对好像这个是什么事件上报qwq

**Comment by TonyLiangP2010405** [comment]
<img width="1280" alt="26b4b19ce9ec20557e434f0dc2d3eb62" src="https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/86188856/81404c04-5b6b-4a17-b3da-904b6e1d9ae1">
 好像是我怎么也上报不成功的原因...

**Comment by PurpleNoon** [comment]
事件上报就是你提供一个地址，然后有新消息来了就发一个事件json给指定的地址，也许你可以看看这个
[HTTP POST](https://github.com/botuniverse/onebot-11/blob/master/communication/http-post.md#http-post)
[事件](https://github.com/botuniverse/onebot-11/blob/master/event/README.md#%E4%BA%8B%E4%BB%B6)

**Comment by TonyLiangP2010405** [comment]
感谢, 但是它好像是fetch不过去我那面按要求配了localhost或者局域网的ip它一直传不过来,图片里面的日志一直在报错qwq

**Comment by PurpleNoon** [comment]
传不过去就是你那边实现的问题了，一般都是需要开一个相应的 http 服务器来接收并处理上报的事件

**Comment by TonyLiangP2010405** [comment]
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/86188856/0adbe105-8a24-46ba-a3fa-a9c015ecccf4)
搞了个内网穿透穿过了了,十分感谢!!!
