### ISSUE TITLE
v3.0.0 bug反馈

### ISSUE THREAD

**Issue by zqwl** [linyuchen/LiteLoaderQQNT-OneBotApi#39]
LLOneBot版本：v3.0.0

1.get_login_info 返回的nickname不对
2.接收图片消息不会自动下载了，例如下方路径并不存在图片，需要自己手动切换到界面才会下载图片
c:\Documents\Tencent Files\123456\nt_qq\nt_data\Pic\2024-02\Ori\9159f537d22d14d7ca88699464d0aa6c.png
上述2个问题旧版没问题

3.艾特群员的data依然为空 
{"data":{},"type":"at"}
4.manifest.json中的version依然是2.5.0

**Comment by linyuchen** [comment]
感谢反馈，[v3.0.1](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已修复，帮忙测试下

**Comment by zqwl** [comment]
LLOneBot版本：v3.0.1

1.get_login_info 返回的nickname依然是账号id而不是昵称

2.图片会自动下载了，但是发送图片消息的时候 不支持本地路径 file://c:/123.jpg 这样的
let url = new URL(uri);
...
await fs.copyFile(url.pathname, filePath);
是不是这里的url.pathname解析的本地路径不不对，另外本地路径可不可以直接发送，不用再复制到数据目录

3.艾特群员的data不是空的了，但是数据不对
{"data":{"mention":"0","qq":"0"},"type":"at"}

4.get_group_list 有时候这个获取群列表只会返回1个群，重启插件后又能获取到完整的

感谢修复

> 感谢反馈，[v3.0.1](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已修复，帮忙测试下

**Comment by linyuchen** [comment]
你的QQ版本号是多少

**Comment by zqwl** [comment]
版本: 9.9.7-21217 (64位)

> 你的QQ版本号是多少

**Comment by linyuchen** [comment]
原来是Windows下有些问题，我说Mac怎么复现不了，[v3.0.2](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已修复

**Comment by linyuchen** [comment]
关于 `本地路径可不可以直接发送，不用再复制到数据目录`，现在改成是不再手动复制一份，但是QQ自身发送还是会自动复制一份到QQ的数据目录的，最终上报自己发送的消息的路径还是QQ数据的路径

**Comment by zqwl** [comment]
> 关于 `本地路径可不可以直接发送，不用再复制到数据目录`，现在改成是不再手动复制一份，但是QQ自身发送还是会自动复制一份到QQ的数据目录的，最终上报自己发送的消息的路径还是QQ数据的路径
感谢回复


发送图片还有个问题
if (process.platform === "win32") {
    filePath = decodeURI(url.pathname.slice(1));
}
这里可能需要解码一下，路径带空格的话会被编码成%20导致发送失败

感谢修复

**Comment by linyuchen** [comment]
> > 关于 `本地路径可不可以直接发送，不用再复制到数据目录`，现在改成是不再手动复制一份，但是QQ自身发送还是会自动复制一份到QQ的数据目录的，最终上报自己发送的消息的路径还是QQ数据的路径
> > 感谢回复
> 
> 发送图片还有个问题 if (process.platform === "win32") { filePath = decodeURI(url.pathname.slice(1)); } 这里可能需要解码一下，路径带空格的话会被编码成%20导致发送失败
> 
> 感谢修复

这个在[v3.0.3](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已经修了

**Comment by zqwl** [comment]
非常感谢！
