### ISSUE TITLE
插件似乎未生效，无法发送消息

### ISSUE THREAD

**Issue by PurpleNoon** [linyuchen/LiteLoaderQQNT-OneBotApi#4]
安装插件后，按照示例发送请求，返回 connect ECONNREFUSED
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/1877d763-702d-48b7-b80b-e7a1a191a97a)
似乎和 [LiteLoaderQQNT-Plugin-LLAPI](https://github.com/linyuchen/LiteLoaderQQNT-Plugin-LLAPI) 未启用有关系
配置：
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/6cb120e6-5bc9-45b8-bac7-08ab08be19e9)

用命令行启动 qq 后的日志：
D:\Program Files\Tencent\QQNT>qq.exe

D:\Program Files\Tencent\QQNT>not mini app.
[app]module file name: D:\Program Files\Tencent\QQNT\QQ.exe
7769277bc358f63dc786c6697c1daaef9b844c4a99d3d74a187e902cc817485e
2a48aa9afca3e84d2930d5fed18084d9132cddcb3921a326c572ef2bc2e7f96e
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
c651b4bfa083cf6aebe2104226131a9dd351d0fd56d4863504bfa7d9f6d5071f
0
[preload] process type:
[app]module file name: D:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.6-19689
[preload] hotupdate current version: 9.9.6-20139
[preload] install app version: 9.9.6-19689

[preload] succeeded. D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.6-20139\wrapper.node
[preload] succeeded. D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.6-20139\major.node
[preload] succeeded. D:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: LLOneBot
[LiteLoader] Found 1 plugins, start loading plugins.
[preload] register done. launcher.node
[preload] register done. major.node
[preload] register done. wrapper.node
14:07:13.046 > [hot update] hotUpdateApi checkHasMultipleQQ false
14:07:13.050 > [hot update] hotUpdateApi start clearOldVersions
14:07:13.051 > [hot update] hotUpdateApi curVersionZipPath is: D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.6-20139.zip false
14:07:13.117 > [hot update] hotUpdateApi checkHasMultipleQQ false
14:07:13.119 > [hot update] hotUpdateApi checkIsOnErrorVersion 9.9.7-20811
14:07:13.121 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false
14:07:13.186 > [hot update] hotUpdateApi cancel
14:07:13.187 > [hot update] onStatusChanged IDLE
14:07:13.189 > [hot update] onUpdateCancel

**Comment by PurpleNoon** [comment]
补充展示放置在LliteLoader 中的插件
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/b69b6f61-1e5c-4404-986e-b361d9db8bea)

**Comment by linyuchen** [comment]
确实是LLAPI的问题，下载新版的应该能解决<https://github.com/linyuchen/LiteLoaderQQNT-Plugin-LLAPI/releases/tag/v1.2.0>

**Comment by PurpleNoon** [comment]
已正常发送消息，非常感谢_(:з」∠)_
