### ISSUE TITLE
3.0.6发群消息文本，返回的sub_type为friend，应该是group

### ISSUE THREAD

**Issue by bianyuan456** [linyuchen/LiteLoaderQQNT-OneBotApi#40]
QQ版本：9.9.7-20979 (64位)

LLOneBot版本：1.0.3

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：自写http客户端，插件形式的。

BUG描述：3.0.6发群消息文本，返回的sub_type为friend，应该是group

复现步骤：在群里发消息，看sub_type

LLOneBot日志:没有这个时间段的日志，找了，就是测试发群消息，没有这部分的日志。

**Comment by linyuchen** [comment]
感谢提醒，[v3.0.7](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)的群消息`sub_type`已改为`normal`，sub_type字段值：https://github.com/botuniverse/onebot-11/blob/master/event/message.md
