### ISSUE TITLE
无法获取上报事件

### ISSUE THREAD

**Issue by CuSO4-55H2O** [linyuchen/LiteLoaderQQNT-OneBotApi#41]
QQ版本：9.9.6-19480 (64位)

LLOneBot版本：3.06

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：自己写的http客户端

BUG描述：
访问本机3000端口
llonebot已启动
终结点get_msg
{"status":-1,"retcode":-1,"data":null,"message":"TypeError: Cannot read properties of undefined (reading 'toString')"}
其他终结点似乎正常
访问本机8080端口（设置的上报地址）或默认地址无法访问

LLOneBot日志:全都是这个
2024/2/14 11:19:48 砰砰机器人(3542366478): 新消息事件上报失败: http://127.0.0.1:8080/ TypeError: fetch failed

**Comment by linyuchen** [comment]
#33
