### ISSUE TITLE
与Websocket服务器握手时出现错误

### ISSUE THREAD

**Issue by EatHatsuneShallots** [linyuchen/LiteLoaderQQNT-OneBotApi#42]
QQ版本：Linux 3.2.5-20811

LLOneBot版本：3.1.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：[ZeroBot](https://github.com/wdvxdr1123/ZeroBot)

BUG描述：ZeroBot无法连接到WebSocket
ZeroBot日志如下
```
INFO[0004] [ws] 开始尝试连接到Websocket服务器: ws://127.0.0.1:11453
WARN[0004] [ws] 与Websocket服务器 ws://127.0.0.1:11453 握手时出现错误: invalid character 'W' looking for beginning of value
```

复现步骤：使用[ZeroBot-Plugin](https://github.com/FloatTech/ZeroBot-Plugin)连接WebSocket

LLOneBot日志:
```
2024/2/16 03:45:34 (xxxxxxxxxxx): event上报ws客户端已连接
2024/2/16 03:45:36 (xxxxxxxxxxx): event上报ws客户端已连接
2024/2/16 03:45:36 (xxxxxxxxxxx): event上报ws客户端已断开
2024/2/16 03:45:37 (xxxxxxxxxxx): event上报ws客户端已断开
```

**Comment by linyuchen** [comment]
[v3.1.1](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已修复

**Comment by EatHatsuneShallots** [comment]
好吧又遇到了一个新的问题（
```
WARN[0036] [ws] 与Websocket服务器 ws://127.0.0.1:xxxxx 握手时出现错误: json: cannot unmarshal string into Go struct field .self_id of type int64
```

**Comment by linyuchen** [comment]
ntqq内部id都是string来的，ZeroBot对id的类型检测比较严格，[v3.1.2](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已修复了这些id的问题

**Comment by EatHatsuneShallots** [comment]
按照OneBot11的规范，WebSocket连接成功后会发送一个叫[https://github.com/botuniverse/onebot-11/blob/master/event/meta.md#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F](生命周期)的事件
能适配吗（

**Comment by linyuchen** [comment]
[v3.2.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已添加

**Comment by EatHatsuneShallots** [comment]
感谢
