### ISSUE TITLE
无法发送和接收QQ表情

### ISSUE THREAD

**Issue by szx0427** [linyuchen/LiteLoaderQQNT-OneBotApi#49]
QQ版本：9.9.7-21484 (64位)

LLOneBot版本：3.2.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：websocket客户端

BUG描述：QQ表情（不是emoji，type是face）发不出去，接收消息时message数组内没有表情对应的元素（会被隔过去），若消息只有一个表情就会像下面日志里一样，message为空。

复现步骤：用websocket按onebot的文档说明发送、接收带QQ表情的消息

LLOneBot日志: （以下QQ号和群号都正常，应该不影响修bug，为保护隐私均隐去，谢谢理解）
新消息事件ws上报 {"self_id":机器人qq号,"user_id":发送者qq号,"time":1708168268,"message_id":1708136861544,"real_id":"7336526847486895820","message_type":"group","sender":{"user_id":发送者qq号,"nickname":"　","card":"","role":"admin"},"raw_message":"","font":14,"sub_type":"normal","message":[{"data":{"text":"测试表情："},"type":"text"},{"data":{"text":"这是表情后面的文字"},"type":"text"}],"post_type":"message","group_id":群号} 
2024/2/17 19:11:11 　(3408556564): 新消息事件HTTP上报失败: http://192.168.1.2:5000/ TypeError: fetch failed{"self_id":机器人qq号,"user_id":发送者qq号,"time":1708168268,"message_id":1708136861544,"real_id":"7336526847486895820","message_type":"group","sender":{"user_id":发送者qq号,"nickname":"　","card":"","role":"admin"},"raw_message":"","font":14,"sub_type":"normal","message":[{"data":{"text":"测试表情："},"type":"text"},{"data":{"text":"这是表情后面的文字"},"type":"text"}],"post_type":"message","group_id":群号}

**Comment by linyuchen** [comment]
[v3.3.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已支持表情
