### ISSUE TITLE
插件似乎未生效x2

### ISSUE THREAD

**Issue by MizurenNanako** [linyuchen/LiteLoaderQQNT-OneBotApi#5]
![2024-01-25_00-40_1](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/29170169/665283ea-b25d-4028-8577-890ff2d1215e)

**已经检查所有issue，LLAPI为 #4 中提及的最新版本。**

**如图，无法正常使用API，启动log如下：**
![2024-01-25_00-40](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/29170169/ed089b9d-31f0-4733-a655-490fc9cf755c)
像上一位 closed 的 issuer 一样使用 chrome 网络台发送请求，得到的结果也是一样的。

**目录结构如下：**
![2024-01-25_00-48](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/29170169/6fb0090b-48b1-4943-8eef-151968d5ab63)

**设置信息如下：**
![2024-01-25_00-43](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/29170169/e5045b83-7480-43b7-afc6-df9b40e595f9)

**版本信息如下：**
![2024-01-25_00-43_1](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/29170169/bb9ddbaa-4120-4d70-8a38-8658c85c9228)
![2024-01-25_00-46](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/29170169/afef05f3-e440-47a8-9c38-65b4f8f9b957)

产生 log **如下：**
![2024-01-25_00-45](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/29170169/7109fcd1-e600-4aea-844e-4bfede164100)

**Comment by MizurenNanako** [comment]
另外，能不能给设置界面的文本框适配一下夜间模式主题？目前在夜间模式下文本框的字也是黑的，和背景一样。

**Comment by linyuchen** [comment]
这是没有适配Linux导致的bug，现已修复，重新下载[LLOneBot](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases/tag/v2.0.1)和[LLAPI](https://github.com/linyuchen/LiteLoaderQQNT-Plugin-LLAPI/releases/tag/v1.2.1)试试

**Comment by MizurenNanako** [comment]
> 这是没有适配Linux导致的bug，现已修复，重新下载[LLOneBot](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases/tag/v2.0.1)和[LLAPI](https://github.com/linyuchen/LiteLoaderQQNT-Plugin-LLAPI/releases/tag/v1.2.1)试试

已完成适配，现一切工作正常，谢谢作者。此 issue 将关闭。
