### ISSUE TITLE
get_group_info和get_group_list的响应数据没有member_count和max_member_count

### ISSUE THREAD

**Issue by bianyuan456** [linyuchen/LiteLoaderQQNT-OneBotApi#50]
QQ版本： 9.9.7-21484 (64位)

LLOneBot版本：3.3.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：精易网页助手

BUG描述：根据 onebot11规范
https://github.com/botuniverse/onebot-11/blob/master/api/public.md#get_group_info-获取群信息
返回的响应数据该有member_count和max_member_count。没有这俩数据不符合onebot11规范。在之前的版本有这个member_count的，我都做好了调用，结果更新了版本后失效了。。。

复现步骤：http://127.0.0.1:3000/get_group_list

LLOneBot日志:不需要

**Comment by linyuchen** [comment]
[v3.3.1](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已修复
