### ISSUE TITLE
[Feature] 支持陌生人私聊消息的发送

### ISSUE THREAD

**Issue by disymayufei** [linyuchen/LiteLoaderQQNT-OneBotApi#57]
尽管OneBot API v11规范中未做出要求，但是现在大部分框架都支持，当检测到```send_private_msg```这一API请求中出现```group_id```字样时，自动判断为从群号为```group_id```这个群中向QQ号为```user_id```的人发送陌生人私聊消息。建议支持这一额外特性，以方便机器人发起私聊消息。

**Comment by linyuchen** [comment]
https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/blob/main/src/onebot11/actions/SendMsg.ts#L40

没有完善，uidmap加进去就行了

**Comment by linyuchen** [comment]
频繁发临时消息容易风控，慎用

**Comment by disymayufei** [comment]
> 频繁发临时消息容易风控，慎用

用原生QQ也会这样吗？

**Comment by linyuchen** [comment]
> > 频繁发临时消息容易风控，慎用
> 
> 用原生QQ也会这样吗？

发的人数过多就会，所以不建议bot主动发临时消息，收就行了
