### ISSUE TITLE
无法连接上云崽、ZeroBot-Plugin实例

### ISSUE THREAD

**Issue by Ray-lea** [linyuchen/LiteLoaderQQNT-OneBotApi#58]
QQ版本：9.9.7-20979

LLOneBot版本：3.3.1

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：云崽（Miao-Yunzai通过[ws-plugin](https://gitee.com/xiaoye12123/ws-plugin)连接）及ZeroBot-Plugin（ws连接）

BUG描述：启用云崽、ZeroBot-Plugin时显示成功连接（见图），但云崽无任何消息进入，发送任何消息均无反应，ZeroBot-Plugin有显示报错（见第二条回复），测试mirai的overflow项目可以正常连接并接收消息。

复现步骤：无

LLOneBot日志:云崽测试时LLOneBot日志仅显示收到新消息，无消息上报及ws连接提示；ZeroBot-Plugin测试时有显示ws客户端已连接及ws消息上报
![3CFB46BB82147A852B8C9B7632E44E1E](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/101520596/5987a7ec-15b2-484a-b294-df5633b0b2b4)
![Snipaste_2024-02-20_00-46-53](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/101520596/346cafe9-2cbc-460c-b709-3cfe64f63d4f)

**Comment by Ray-lea** [comment]
ZeroBot-Plugin出现报错
![Uploading Snipaste_2024-02-20_19-39-27.png…]()

**Comment by Ray-lea** [comment]
LLonebot的设置
![Snipaste_2024-02-20_20-01-58](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/101520596/bada58dc-d3d8-412e-ba99-08119b170803)

**Comment by Ray-lea** [comment]
> 云崽改为反向ws时，有出现报错： ![C3CEFDB44621C1DEE9FA4F298A420633](https://private-user-images.githubusercontent.com/101520596/306252870-50d6366c-bad6-4b5f-921c-2a20dc844d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzA4NTQsIm5iZiI6MTcwODQzMDU1NCwicGF0aCI6Ii8xMDE1MjA1OTYvMzA2MjUyODcwLTUwZDYzNjZjLWJhZDYtNGI1Zi05MjFjLTJhMjBkYzg0NGQzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMjAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjFlNzM5M2IwZDFjOGFjYmJkODIxZGY5NWRjNWY4NDA3NjIzMTkwY2EzZTBjNzNiMTBmNzgyMDIzMGE0YjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RDBvjwgT9jla0iI9A3g55AaKAhMgzfkw1YE-Mxsa-IE) ![DAE4E2316062BC2C241C95FA21397805](https://private-user-images.githubusercontent.com/101520596/306252884-d0cf5787-9ccf-46b1-8b4f-19022c6dc383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzA4NTQsIm5iZiI6MTcwODQzMDU1NCwicGF0aCI6Ii8xMDE1MjA1OTYvMzA2MjUyODg0LWQwY2Y1Nzg3LTljY2YtNDZiMS04YjRmLTE5MDIyYzZkYzM4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMjAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGRmYjJmODk5NTY0OGQ1ZDk4NDE5YmM0NWYxNDFkNTEwMGY2ODgzZDNhY2U2MWU0ODMxMzdhMTJmNTg1OTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j5I5TFd5C-sygOUMR7cPjda-KtaJ1o_c1DdRhuU05cA)

是不是不能一边正向一边反向的来着（不太懂）

**Comment by linyuchen** [comment]
1.检查你的zerobot使用的协议是不是标准的onebot 11，我看到了`make_msg_as_read`这个api，这不是onebot11里面的

2.目前还不支持反向ws，下版本会支持，没有用过云崽，你看看有没有可以设置正向ws连接的

**Comment by Ray-lea** [comment]
> 1.检查你的zerobot使用的协议是不是标准的onebot 11，我看到了`make_msg_as_read`这个api，这不是onebot11里面的
> 
> 2.目前还不支持反向ws，下版本会支持，没有用过云崽，你要先确定云崽那个ws-plugin支不支持onebot11，你看看有没有可以设置正向ws连接的

云崽测试时使用的是正向ws，LLOneBot日志仅显示收到新消息，无消息上报及ws连接提示，云崽显示CQ WebSocket 服务己启动
![Snipaste_2024-02-20_00-46-53](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/101520596/05bfa3cc-7781-4ad5-984b-a8153e050558)

**Comment by linyuchen** [comment]
> > 1.检查你的zerobot使用的协议是不是标准的onebot 11，我看到了`make_msg_as_read`这个api，这不是onebot11里面的
> > 2.目前还不支持反向ws，下版本会支持，没有用过云崽，你要先确定云崽那个ws-plugin支不支持onebot11，你看看有没有可以设置正向ws连接的
> 
> 云崽测试时使用的是正向ws，LLOneBot日志仅显示收到新消息，无消息上报及ws连接提示，云崽显示CQ WebSocket 服务己启动 ![Snipaste_2024-02-20_00-46-53](https://private-user-images.githubusercontent.com/101520596/306262740-05bfa3cc-7781-4ad5-984b-a8153e050558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzI4ODAsIm5iZiI6MTcwODQzMjU4MCwicGF0aCI6Ii8xMDE1MjA1OTYvMzA2MjYyNzQwLTA1YmZhM2NjLTc3ODEtNGFkNS05ODRiLWE4MTUzZTA1MDU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMjM2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDI0ZWI1ODc4Y2Q2ZTMyYjJiMjcxN2UxZmYwY2ViOGZjYjhhYzFiZmEwZjRjNjU4ZmYyZGVhMzQ1MzhlNTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C95gkOb9Sl8ykk9qcNjgczJ_rHj1lds-t2SGg-gjn_M)

我感觉你可能弄错了，这云崽的ws-plugin不是作为应用端的吧，他是个协议端，是不是会登录你的QQ？是给zerobot、overflow对接的吧

**Comment by Ray-lea** [comment]
> 1.检查你的zerobot使用的协议是不是标准的onebot 11，我看到了`make_msg_as_read`这个api，这不是onebot11里面的
> 
> 2.目前还不支持反向ws，下版本会支持，没有用过云崽，你要先确定云崽那个ws-plugin支不支持onebot11，你看看有没有可以设置正向ws连接的

zerobot使用onebot 11后，能正常收到消息但无消息内容
![Snipaste_2024-02-20_20-40-48](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/101520596/813d3d29-fdee-480f-aaf3-3033f6069d23)
![Snipaste_2024-02-20_20-40-48](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/101520596/662e30dd-c3d9-4e06-9ad4-6a3cd1c23a64)

**Comment by Ray-lea** [comment]
> > > 1.检查你的zerobot使用的协议是不是标准的onebot 11，我看到了`make_msg_as_read`这个api，这不是onebot11里面的
> > > 2.目前还不支持反向ws，下版本会支持，没有用过云崽，你要先确定云崽那个ws-plugin支不支持onebot11，你看看有没有可以设置正向ws连接的
> > 
> > 
> > 云崽测试时使用的是正向ws，LLOneBot日志仅显示收到新消息，无消息上报及ws连接提示，云崽显示CQ WebSocket 服务己启动 ![Snipaste_2024-02-20_00-46-53](https://private-user-images.githubusercontent.com/101520596/306262740-05bfa3cc-7781-4ad5-984b-a8153e050558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzI4ODAsIm5iZiI6MTcwODQzMjU4MCwicGF0aCI6Ii8xMDE1MjA1OTYvMzA2MjYyNzQwLTA1YmZhM2NjLTc3ODEtNGFkNS05ODRiLWE4MTUzZTA1MDU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMjM2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDI0ZWI1ODc4Y2Q2ZTMyYjJiMjcxN2UxZmYwY2ViOGZjYjhhYzFiZmEwZjRjNjU4ZmYyZGVhMzQ1MzhlNTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C95gkOb9Sl8ykk9qcNjgczJ_rHj1lds-t2SGg-gjn_M)
> 
> 我感觉你可能弄错了，这云崽的ws-plugin不是作为应用端的吧，他是个协议端，是不是会登录你的QQ？是给zerobot、overflow对接的吧

不会登录我qq啊，我看项目页是写“Yunzai-Bot 的扩展插件 ws-plugin 提供ontbot协议适配,通过WebSocket连接onebot实现的bot”

**Comment by XZhouQD** [comment]
> > > > 1.检查你的zerobot使用的协议是不是标准的onebot 11，我看到了`make_msg_as_read`这个api，这不是onebot11里面的
> > > > 2.目前还不支持反向ws，下版本会支持，没有用过云崽，你要先确定云崽那个ws-plugin支不支持onebot11，你看看有没有可以设置正向ws连接的
> > > 
> > > 
> > > 云崽测试时使用的是正向ws，LLOneBot日志仅显示收到新消息，无消息上报及ws连接提示，云崽显示CQ WebSocket 服务己启动 ![Snipaste_2024-02-20_00-46-53](https://private-user-images.githubusercontent.com/101520596/306262740-05bfa3cc-7781-4ad5-984b-a8153e050558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzI4ODAsIm5iZiI6MTcwODQzMjU4MCwicGF0aCI6Ii8xMDE1MjA1OTYvMzA2MjYyNzQwLTA1YmZhM2NjLTc3ODEtNGFkNS05ODRiLWE4MTUzZTA1MDU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMjM2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDI0ZWI1ODc4Y2Q2ZTMyYjJiMjcxN2UxZmYwY2ViOGZjYjhhYzFiZmEwZjRjNjU4ZmYyZGVhMzQ1MzhlNTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C95gkOb9Sl8ykk9qcNjgczJ_rHj1lds-t2SGg-gjn_M)
> > 
> > 
> > 我感觉你可能弄错了，这云崽的ws-plugin不是作为应用端的吧，他是个协议端，是不是会登录你的QQ？是给zerobot、overflow对接的吧
> 
> 不会登录我qq啊，我看[项目页](https://gitee.com/xiaoye12123/ws-plugin)是写“Yunzai-Bot 的扩展插件 ws-plugin 提供ontbot协议适配,通过WebSocket连接onebot实现的bot”

ws-plugin是装在已连接其他协议端的Miao-Yunzai或TRSS-Yunzai里，给其他服务提供onebot的……比如你可以形成 icqq => Miao-Yunzai => ws-plugin => nonebot2这样子

**Comment by XZhouQD** [comment]
> > > > > > 1.检查你的zerobot使用的协议是不是标准的onebot 11，我看到了`make_msg_as_read`这个api，这不是onebot11里面的
> > > > > > 2.目前还不支持反向ws，下版本会支持，没有用过云崽，你要先确定云崽那个ws-plugin支不支持onebot11，你看看有没有可以设置正向ws连接的
> > > > > 
> > > > > 
> > > > > 云崽测试时使用的是正向ws，LLOneBot日志仅显示收到新消息，无消息上报及ws连接提示，云崽显示CQ WebSocket 服务己启动 ![Snipaste_2024-02-20_00-46-53](https://private-user-images.githubusercontent.com/101520596/306262740-05bfa3cc-7781-4ad5-984b-a8153e050558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzI4ODAsIm5iZiI6MTcwODQzMjU4MCwicGF0aCI6Ii8xMDE1MjA1OTYvMzA2MjYyNzQwLTA1YmZhM2NjLTc3ODEtNGFkNS05ODRiLWE4MTUzZTA1MDU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMjM2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDI0ZWI1ODc4Y2Q2ZTMyYjJiMjcxN2UxZmYwY2ViOGZjYjhhYzFiZmEwZjRjNjU4ZmYyZGVhMzQ1MzhlNTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C95gkOb9Sl8ykk9qcNjgczJ_rHj1lds-t2SGg-gjn_M)
> > > > 
> > > > 
> > > > 我感觉你可能弄错了，这云崽的ws-plugin不是作为应用端的吧，他是个协议端，是不是会登录你的QQ？是给zerobot、overflow对接的吧
> > > 
> > > 
> > > 不会登录我qq啊，我看[项目页](https://gitee.com/xiaoye12123/ws-plugin)是写“Yunzai-Bot 的扩展插件 ws-plugin 提供ontbot协议适配,通过WebSocket连接onebot实现的bot”
> > 
> > 
> > ws-plugin是装在已连接其他协议端的Miao-Yunzai或TRSS-Yunzai里，给其他服务提供onebot的……比如你可以形成 icqq => Miao-Yunzai => ws-plugin => nonebot2这样子
> 
> 这意味着我不能直接通过 ws-plugin 使云崽连接LLOneBot，而是需要先通过 icqq在云崽内登录，然后才能使用ws-plugin连接其他如nonebot2，有点绕晕

正确的，ws-plugin作为server的是连接GSCore和Red，所以你应当用本插件支持反向ws的版本，使用Lain-Plugin或TRSS-Yunzai来连接

**Comment by Ray-lea** [comment]
> > > > > > > 1.检查你的zerobot使用的协议是不是标准的onebot 11，我看到了`make_msg_as_read`这个api，这不是onebot11里面的
> > > > > > > 2.目前还不支持反向ws，下版本会支持，没有用过云崽，你要先确定云崽那个ws-plugin支不支持onebot11，你看看有没有可以设置正向ws连接的
> > > > > > 
> > > > > > 
> > > > > > 云崽测试时使用的是正向ws，LLOneBot日志仅显示收到新消息，无消息上报及ws连接提示，云崽显示CQ WebSocket 服务己启动 ![Snipaste_2024-02-20_00-46-53](https://private-user-images.githubusercontent.com/101520596/306262740-05bfa3cc-7781-4ad5-984b-a8153e050558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzI4ODAsIm5iZiI6MTcwODQzMjU4MCwicGF0aCI6Ii8xMDE1MjA1OTYvMzA2MjYyNzQwLTA1YmZhM2NjLTc3ODEtNGFkNS05ODRiLWE4MTUzZTA1MDU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMjM2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDI0ZWI1ODc4Y2Q2ZTMyYjJiMjcxN2UxZmYwY2ViOGZjYjhhYzFiZmEwZjRjNjU4ZmYyZGVhMzQ1MzhlNTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C95gkOb9Sl8ykk9qcNjgczJ_rHj1lds-t2SGg-gjn_M)
> > > > > 
> > > > > 
> > > > > 我感觉你可能弄错了，这云崽的ws-plugin不是作为应用端的吧，他是个协议端，是不是会登录你的QQ？是给zerobot、overflow对接的吧
> > > > 
> > > > 
> > > > 不会登录我qq啊，我看[项目页](https://gitee.com/xiaoye12123/ws-plugin)是写“Yunzai-Bot 的扩展插件 ws-plugin 提供ontbot协议适配,通过WebSocket连接onebot实现的bot”
> > > 
> > > 
> > > ws-plugin是装在已连接其他协议端的Miao-Yunzai或TRSS-Yunzai里，给其他服务提供onebot的……比如你可以形成 icqq => Miao-Yunzai => ws-plugin => nonebot2这样子
> > 
> > 
> > 这意味着我不能直接通过 ws-plugin 使云崽连接LLOneBot，而是需要先通过 icqq在云崽内登录，然后才能使用ws-plugin连接其他如nonebot2，有点绕晕
> 
> 正确的，ws-plugin作为server的是连接GSCore和Red，所以你应当用本插件支持反向ws的版本，使用Lain-Plugin或TRSS-Yunzai来连接

好的，感谢你的回复

**Comment by Ray-lea** [comment]
> > 1.检查你的zerobot使用的协议是不是标准的onebot 11，我看到了`make_msg_as_read`这个api，这不是onebot11里面的
> > 2.目前还不支持反向ws，下版本会支持，没有用过云崽，你要先确定云崽那个ws-plugin支不支持onebot11，你看看有没有可以设置正向ws连接的
> 
> zerobot使用onebot 11后，能正常收到消息但无消息内容 ![Snipaste_2024-02-20_20-40-48](https://private-user-images.githubusercontent.com/101520596/306264615-813d3d29-fdee-480f-aaf3-3033f6069d23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzUyNTQsIm5iZiI6MTcwODQzNDk1NCwicGF0aCI6Ii8xMDE1MjA1OTYvMzA2MjY0NjE1LTgxM2QzZDI5LWZkZWUtNDgwZi1hYWYzLTMwMzNmNjA2OWQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMzE1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZThkYmI1YjliZTM4ZmJlOGFmY2ZjNWNlYzkwNTNkMDM4ZDc3ZTBlNGRkOGE4OTg0ODgyNzc0Y2Y5ODdlZDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9Ay0FhqOLCflouqxWHopN0Gk9hvtEw-OSJNDpOJDCdI) ![Snipaste_2024-02-20_20-40-24](https://private-user-images.githubusercontent.com/101520596/306264868-d0e3c6d2-3030-48b2-89a0-3f48d3e437fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzUyNTQsIm5iZiI6MTcwODQzNDk1NCwicGF0aCI6Ii8xMDE1MjA1OTYvMzA2MjY0ODY4LWQwZTNjNmQyLTMwMzAtNDhiMi04OWEwLTNmNDhkM2U0MzdmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMzE1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDEwYTU0OTdmYjdkYzRjMmRlMGIwZTkwZTZhZjNlNGMzNDcxYmM3ZWE5MzFjZWU2NGZiYzlmYzViNDVjY2JkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dmf858caeaVJfr59-r6ur5YB9l5kIjEY7xc7YTXDBKY)

为避免此消息被回复覆盖，重新引用一下该内容。

**Comment by linyuchen** [comment]
[v3.5.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已修复

**Comment by Ray-lea** [comment]
> [v3.5.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已修复

测试接受消息成功，但仍有部分bug：图片消息显示为空消息，和发送部分消息出现如图所示报错

**Comment by linyuchen** [comment]
1.据我所知这个日志显示用的是raw_message字段，这个字段应该是不影响zerobot解析的吧，所以空不空应该是无所谓的

2.是什么场景需要调用get_stranger_info？

**Comment by Ray-lea** [comment]
> 1.据我所知这个日志显示用的是raw_message字段，这个字段应该是不影响zerobot解析的吧，所以空不空应该是无所谓的
> 
> 2.是什么场景需要调用get_stranger_info？

在使用zerobot的“/服务列表”功能时所出现的

**Comment by linyuchen** [comment]
> > 1.据我所知这个日志显示用的是raw_message字段，这个字段应该是不影响zerobot解析的吧，所以空不空应该是无所谓的
> > 2.是什么场景需要调用get_stranger_info？
> 
> 在使用zerobot的“/服务列表”功能时所出现的

具体一点，私聊还是群聊，你发消息的账号和bot不是好友吗

**Comment by Ray-lea** [comment]
> > > 1.据我所知这个日志显示用的是raw_message字段，这个字段应该是不影响zerobot解析的吧，所以空不空应该是无所谓的
> > > 2.是什么场景需要调用get_stranger_info？
> > 
> > 
> > 在使用zerobot的“/服务列表”功能时所出现的
> 
> 具体一点，私聊还是群聊，你发消息的账号和bot不是好友吗

是群聊，和发消息账号和bot是好友

**Comment by linyuchen** [comment]
> > > > 1.据我所知这个日志显示用的是raw_message字段，这个字段应该是不影响zerobot解析的吧，所以空不空应该是无所谓的
> > > > 2.是什么场景需要调用get_stranger_info？
> > > 
> > > 
> > > 在使用zerobot的“/服务列表”功能时所出现的
> > 
> > 
> > 具体一点，私聊还是群聊，你发消息的账号和bot不是好友吗
> 
> 是群聊，发消息账号和bot是好友

所以就很奇怪，这个`get_stranger_info`是用来获取陌生人信息的，为啥会调用这个。。。
我测试的时候发送`/服务列表`是能够正常返回的，你那边是没有响应吗

**Comment by Ray-lea** [comment]
> > > > > 1.据我所知这个日志显示用的是raw_message字段，这个字段应该是不影响zerobot解析的吧，所以空不空应该是无所谓的
> > > > > 2.是什么场景需要调用get_stranger_info？
> > > > 
> > > > 
> > > > 在使用zerobot的“/服务列表”功能时所出现的
> > > 
> > > 
> > > 具体一点，私聊还是群聊，你发消息的账号和bot不是好友吗
> > 
> > 
> > 是群聊，发消息账号和bot是好友
> 
> 所以就很奇怪，这个`get_stranger_info`是用来获取陌生人信息的，为啥会调用这个。。。 我测试的时候发送`/服务列表`是能够正常返回的，你那边是没有响应吗

另使用点歌功能时出现报错
![Snipaste_2024-02-21_18-55-21](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/101520596/7fdacf32-d005-48e1-95ff-02d107c80944)

**Comment by linyuchen** [comment]
点歌在NTQQ上不好搞，我不清楚之前你们用的点歌功能是什么样的，是群里的一起听歌吗，还是分享一个QQ音乐卡片

`/功能列表`图片为空应该是zerobot-plugin的问题，在`ZeroBot-Plugin/data/zbpbanner/`下图片都是打不开的，可能是图片服务挂了？

**Comment by Ray-lea** [comment]
> 点歌在NTQQ上不好搞，我不清楚之前你们用的点歌功能是什么样的，是群里的一起听歌吗，还是分享一个QQ音乐卡片
> 
> `/功能列表`图片为空应该是zerobot-plugin的问题，在`ZeroBot-Plugin/data/zbpbanner/`下图片都是打不开的，可能是图片服务挂了？

点歌一般是分享音乐卡片

应该是是服务挂了，我在用所有基于api的服务都会出现503，不太懂zerobot这边出了啥问题。
“ERROR: Get "http://api.qingyunke.com/api.php?key=free&appid=0&msg=%2F%E6%B8%A3%E6%88%91": dial tcp 42.192.160.185:80: connectex: No connection could be made because the target machine actively refused it.@0.0 ”
“ERROR: status code: 503”

**Comment by EatHatsuneShallots** [comment]
> > > > > > 1.据我所知这个日志显示用的是raw_message字段，这个字段应该是不影响zerobot解析的吧，所以空不空应该是无所谓的
> > > > > > 2.是什么场景需要调用get_stranger_info？
> > > > > 
> > > > > 
> > > > > 在使用zerobot的“/服务列表”功能时所出现的
> > > > 
> > > > 
> > > > 具体一点，私聊还是群聊，你发消息的账号和bot不是好友吗
> > > 
> > > 
> > > 是群聊，发消息账号和bot是好友
> > 
> > 所以就很奇怪，这个`get_stranger_info`是用来获取陌生人信息的，为啥会调用这个。。。 我测试的时候发送`/服务列表`是能够正常返回的，你那边是没有响应吗
> 
> 有响应，但返回功能图片中，所有具体功能的图片为空（如图，不确定是不是LLonebot的问题），另附带发送消息前后的LLonebot日志
> ![7C967E921E827AD80BB14B532BE0CB06](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/101520596/2b85a3b6-2d24-4145-b289-fdd9417e6ca7)
> [日志.txt](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/files/14358342/default.txt)
> 

这个好像是ZeroBot-Plugin的问题，因为我用go-cqhttp也会出现这种问题。
