### ISSUE TITLE
对接 NoneBot-Adapter-OneBot 时消息事件上报失败

### ISSUE THREAD

**Issue by PurpleNoon** [linyuchen/LiteLoaderQQNT-OneBotApi#6]
在对接 NoneBot2 OneBot 适配器时，发现上报消息事件时，缺少 raw_message 和 font 两个字段，导致上报失败
在测试中，发现上报数据中，补充添加 {"raw_message": "", "font": 0}，即可上报成功（不过这样的话， raw_message 的实际内容是错误的，且查看 onebot-v11 文档后，并未发现如何处理 raw_message 的相关信息，不知道作者要如何处理 raw_message，要转 cq 码吗？）

添加字段后上报成功的示例：
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/4de1ed6f-5043-4a5d-ae45-cf56181667d0)

参考的文档：[[onebot-v11]群消息事件数据](https://github.com/botuniverse/onebot-11/blob/master/event/message.md#%E4%BA%8B%E4%BB%B6%E6%95%B0%E6%8D%AE-1)
NoneBot2 OneBot 适配器项目地址：[NoneBot2 OneBot 适配器](https://github.com/nonebot/adapter-onebot)

**Comment by linyuchen** [comment]
raw_message实际上是cq码格式的，但是现在cq码已经过时了，所以不打算支持cq码，或许以后会有人提pr来支持。

我理解的raw_message和message字段功能是一样的，已经有了message字段，适配器应该会正确解析到消息，所以raw_message为空字符串应当不影响（我也不确定）。

我没有用到NoneBot2 OneBot的适配器，所以麻烦你测试一下raw_message为空字符串是否会影响消息解析，能否正确拿到消息内容。

另外font的话，ntqq上所有人的字体都是一样的，暂时就随便设个值了。

**Comment by PurpleNoon** [comment]
经过测试，结果如下：
raw_message 为空字符串时，应当是不影响消息解析，适配器内部提取命令后参数函数的执行结果也是正确的。不过，直接获取 raw_message，是返回空字符串的，在下图中也可以看到。
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/17242220-91a1-4dd5-a8d3-ad08259d1ddd)
最后，在 NoneBot2 OneBot的适配器源码中搜索 raw_message，只找到了消息事件中定义的 raw_message 字段，除测试部分外，未找到相关的处理逻辑，推测 raw_message 为空字符串时，影响应该不大
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/9b785039-43cf-4766-bf8a-b8a27cb4d85f)

**Comment by linyuchen** [comment]
感谢测试，我已经将raw_message和font字段添加到了上报消息体中，<https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases/tag/v2.0.2>

**Comment by PurpleNoon** [comment]
好的，现在 NoneBot2 OneBot 适配器已经能够正常收到上报的消息事件了，感谢_(:з」∠)_

**Comment by yhzcake** [comment]
你好,请问怎么连nonebot2 onebot?我设置了nonebot的配置
HOST=127.0.0.1
PORT=7000
ONEBOT_API_ROOTS={"1367808860":"http://127.0.0.1:3000/"}

**Comment by linyuchen** [comment]
> 你好,请问怎么连nonebot2 onebot?我设置了nonebot的配置 HOST=127.0.0.1 PORT=7000 ONEBOT_API_ROOTS={"1367808860":"[http://127.0.0.1:3000/"}](http://127.0.0.1:3000/%22%7D) 并设置了 ![image](https://private-user-images.githubusercontent.com/80627671/301835732-6c03abfe-a18b-49f2-b432-7c871cdd01ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzUzODcsIm5iZiI6MTcwNjg3NTA4NywicGF0aCI6Ii84MDYyNzY3MS8zMDE4MzU3MzItNmMwM2FiZmUtYTE4Yi00OWYyLWI0MzItN2M4NzFjZGQwMWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDExNTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ODcwZTlhNTI2MjNlNDRiMjdkYzExYzM4OTdkNGI0N2RiODRjNWE5MzM3ODI1Yzk1OTBjMjEyOWE1NDAxMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oJFA8q6g9V8d9yXwUrv0XT8clZtOqtxxFkWfZjFKkF8) 但是貌似接受不到上报的消息 不知道是哪里出了问题? 是新生成的nb2实例,没做任何其他更改 ![image](https://private-user-images.githubusercontent.com/80627671/301836066-d84b2663-bd49-41b2-93ad-29209c78a47b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzUzODcsIm5iZiI6MTcwNjg3NTA4NywicGF0aCI6Ii84MDYyNzY3MS8zMDE4MzYwNjYtZDg0YjI2NjMtYmQ0OS00MWIyLTkzYWQtMjkyMDljNzhhNDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDExNTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOTRjNmZiMWE4NzViMmRmYjgwZGI0ODNhOTdlNTA3ZDdhOWVlNmZhZjc0ZmMyM2EwMWQ1YmQyZjBlMjAzOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rhn7xFwU86OGk9m2LIMBoaJJqsRbdeI4ELX44BFLfy8) 图片li里的几个get是我在浏览器里访问出现的

可能是和[#10](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/issues/10)一样的问题

查看日志是否有上报

1.127.0.0.1改成局域网的ip试一下
2.多重启QQ几次试一下

**Comment by yhzcake** [comment]
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/80627671/211f5fdf-f46f-4b3e-8802-fe62b814a7ab)
日志是这样子的,里面几个post请求是我手动尝试的..
是nonebot和qq都改成局域网ip吗,我去试试

**Comment by yhzcake** [comment]
改过了,重启也重启过,貌似还是不行
日志里也还是什么都没

**Comment by linyuchen** [comment]
> 改过了,重启也重启过,貌似还是不行 日志里也还是什么都没

删除`LiteLoaderQQNT/data/LLOneBot/config_*.json`再重启QQ试一下，还不行就单独开个issue附上QQ版本和相关插件版本号

**Comment by PurpleNoon** [comment]
这是我的配置
NoneBot：
PORT=5000  # 配置 NoneBot2 监听的端口
driver=~fastapi+~httpx+~websockets
ONEBOT_API_ROOTS={"2435658320": "http://127.0.0.1:3000/"}
LLOneBot：
监听端口：3000
事件上报地址：http://127.0.0.1:5000/onebot/v11/

我的检查方式：（我只启动了一个qqnt）
检查 qqnt 安装目录下 \resources\app\app_launcher\LiteLoaderQQNT\data\LLOneBot 目录下是否只有 config_${qq}.json，如果有其他json，删掉（当时我还更新了一下两个插件，不过看了一下另一个 issues，你的两个插件应当是最新的），然后就好使了
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/f4c56248-0dfe-4e48-b492-b2ca8e63c2ec)

如果上述方式不行，看看是否启动了多个 qqnt，我是只启动了一个，检查 qqnt 登录的 qq 是否是在线状态，指定群聊是否是允许消息提醒
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/aa758ec3-5906-401a-8875-7574c60c64c7)

如果还是不行，可以考虑参考一下我的 debug 方式，向作者进行反馈qwq
1. cmd打开qqnt目录，输入 chcp 65001 回车后输出 qq.exe，登录qq
2. 等待登录完成后，检查 LLOneBot 监听服务是否已启动，如果没启动，就不正常
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/84cd1663-b439-45c6-899f-47b2f3f3704e)
3. 在指定群发送消息，检查 cmd 输出是否有上报消息，如果没有如图红框部分显示，则不正常
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/9cc917fd-34d2-4d1c-ad94-5db7a82ca68a)
4. 检查 NoneBot 机器人控制台输出，如果没有如图红框部分，则不正常
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/24586760/db6971a1-56e3-48c5-8a48-c220c35c8db0)
5. 如果如上检查后，你的 NoneBot 事件处理无法接受到消息，则可能是你的 NoneBot 编写有问题
