### ISSUE TITLE
[Bug]: 调用 send_private_forward_msg 时出现错误, 返回值: 1404 , 信息:  解释:

### ISSUE THREAD

**Issue by EatHatsuneShallots** [linyuchen/LiteLoaderQQNT-OneBotApi#60]
QQ版本：Linux 3.2.5-20811 arm64

LLOneBot版本：v3.4.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：ZeroBot

BUG描述：无法发送合并转发消息：缺失接口`send_private_forward_msg`

复现步骤：调用`send_private_forward_msg`接口

LLOneBot日志: 不需要

**Comment by linyuchen** [comment]
[v3.5.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已支持
