### ISSUE TITLE
调用 send_group_forward_msg 时出现错误, 返回值: 1404, 解释: bug

### ISSUE THREAD

**Issue by 23650** [linyuchen/LiteLoaderQQNT-OneBotApi#61]
QQ版本：9.9.7-21484 (windows)

LLOneBot版本：3.4.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：NoneBot2（zhenxunBot）

BUG描述：bot发送合并转发消息时发生错误，导致无法正常发送；

复现步骤：用户请求多张图片 -> bot收到后开始下载 -> 全部下载完成，开始合并转发发送 -> 发送出错 -> 没有收到任何返回消息

LLOneBot日志: https://paste.ubuntu.com/p/93w9RZTZK4/

NoneBot 日志：nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1404, data=None, echo='2231', message='不支持的api send_group_forward_msg')

**Comment by linyuchen** [comment]
[v3.5.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已支持

**Comment by 23650** [comment]
新版本可以正常发送了，赞美开发！
