### ISSUE TITLE
[提问] 服务器如何将http服务绑定至内网ip

### ISSUE THREAD

**Issue by blyc** [linyuchen/LiteLoaderQQNT-OneBotApi#62]
如题，用的tx云轻量 服务器1 部署bot，同时有公网ip和内网ip，
在同一内网的另一台 服务器2 测试发现在只能用公网ip访问 服务器1的api，而不能用内网ip访问
故想咨询是否有可选绑定ip的方法或其他解决办法？

**Comment by linyuchen** [comment]
默认是绑定所有ip的，你先在服务器1用内网ip自己访问自己试试

* 用命令行查看绑定的端口和ip情况
* 如果内网网卡没有绑定自行用nginx之类的http服务转发一下
* 检查防火墙是否允许了LLOneBot的端口

**Comment by blyc** [comment]
感谢解答，反复确认后是我用的api测试工具的问题
并且还感谢提供了用nginx的思路，有点思维定式了没想到还能这样处理
