### ISSUE TITLE
希望添加新的API(get_msg)支持，私聊消息上报没有sender

### ISSUE THREAD

**Issue by Apricityx** [linyuchen/LiteLoaderQQNT-OneBotApi#8]
在对接koishi时出现问题，希望添加新的API支持
相关issue：https://github.com/koishijs/koishi-plugin-adapter-onebot/issues/12

**Comment by linyuchen** [comment]
get_msg的api现在不打算支持，也不影响使用

私聊消息sender没有找到的bug已修复，[v2.0.4](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases/tag/v2.0.4)

**Comment by Apricityx** [comment]
测试发现文字消息能正常发送，图片消息发送不了，koishi端无报错

**Comment by Apricityx** [comment]
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/78242039/61022684-e9f0-43b5-9ce1-ab22cbc2a718)
koishi版本：4.16.7（最新）
发送图片的插件名：nlr-meme或xibao
未找到llonebot.log

**Comment by linyuchen** [comment]
你是不是把QQ装C盘去了，导致没有权限写入文件，你装到别的盘符试试

**Comment by Apricityx** [comment]
> 你是不是把QQ装C盘去了，导致没有权限写入文件，你装到别的盘符试试

改了安装位置，日志能正常生成。
但我换了个网络环境，导致现在上报地址无论怎么换都无法正常上报到koishi，且日志没有任何报错，是否方便添加相关的调试信息，例如是否正常上报，便于我进行debug

**Comment by linyuchen** [comment]
> > 你是不是把QQ装C盘去了，导致没有权限写入文件，你装到别的盘符试试
> 
> 改了安装位置，日志能正常生成。 但我换了个网络环境，导致现在上报地址无论怎么换都无法正常上报到koishi，且日志没有任何报错，是否方便添加相关的调试信息，例如是否正常上报或接收到消息后尝试上报，便于我进行debug

日志中有上报的信息，如果没有尝试重启QQ，有可能是QQ多开导致的bug
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/10002169/f4edf147-6540-430b-b1d7-7c36be134c15)

**Comment by Apricityx** [comment]
很奇怪，日志并没有任何反应，但显示koishi确实向QQNT获取了bot的信息，插件，qq，koishi插件均为最新版本
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/78242039/c87b33d3-d076-4d00-bc54-105ff8bea8f6)

**Comment by linyuchen** [comment]
> 把端口从3001换到3000就正常了，图片也能正常发出来，日志也正常了

emmmm，检查下是不是有别的程序占用了端口

**Comment by Apricityx** [comment]
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/78242039/e5ba9bf3-f6df-4afb-8887-cb93c67181a3)
应该是没有

**Comment by Apricityx** [comment]
我再换个端口看能不能复现问题

**Comment by Apricityx** [comment]
![image](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/assets/78242039/a40f1261-53cc-4e7e-8f21-4f05cbf57544)
确实是换其它任意端口就不上报消息

**Comment by linyuchen** [comment]
> ![image](https://private-user-images.githubusercontent.com/78242039/301043683-a40f1261-53cc-4e7e-8f21-4f05cbf57544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2Nzc4NDAsIm5iZiI6MTcwNjY3NzU0MCwicGF0aCI6Ii83ODI0MjAzOS8zMDEwNDM2ODMtYTQwZjEyNjEtNTNjYy00ZTdlLThmMjEtNGYwNWNiZjU3NTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA1MDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZjcwOTcwZjMyYjY3ZjdjNWMzMjYxNjYyNjcwYTQ1NzQyODVkNmU0MTAxM2NlNWFjN2IxODU5ZjZhMGZkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ETRWYKBqGZ8dM-p_ROGYbfyIY-8y8xp6MD9kQywTA5A) 确实是换其它任意端口就不上报消息

检查下`LiteLoaderQQNT/data/LLOneBot/config_<qq>.json`里面的配置是不是正常的

**Comment by linyuchen** [comment]
我大概找到原因，你是不是同时登录了多个QQ，大概是这个导致的bug

**Comment by Apricityx** [comment]
> 我大概找到原因，你是不是同时登录了多个QQ，大概是这个导致的bug，这个我还没有找到具体是什么原因会导致这样，目前的解决方案是，再次重新登录

目前测试发现和端口具体是多少没有关系，发现每次重启QQ都有较大的概率无法发送消息。没有同时登陆多个QQ，但曾经有其他账号登陆过，在删除LiteLoaderQQNT-main\data\LLOneBot下其他账号的配置文件后可以稳定运行

**Comment by linyuchen** [comment]
> > 我大概找到原因，你是不是同时登录了多个QQ，大概是这个导致的bug，这个我还没有找到具体是什么原因会导致这样，目前的解决方案是，再次重新登录
> 
> 目前测试发现和端口具体是多少没有关系，发现每次重启QQ都有较大的概率无法发送消息。没有同时登陆多个QQ，但曾经有其他账号登陆过，在删除LiteLoaderQQNT-main\data\LLOneBot下其他账号的配置文件后可以稳定运行

感谢测试，这个问题单独开个issue吧
