### ISSUE TITLE
好友请求上报 格式有问题和onebot格式不匹配

### ISSUE THREAD

**Issue by airdm** [linyuchen/LiteLoaderQQNT-OneBotApi#86]
LLOneBot版本：3.8.1

[好友添加](https://github.com/botuniverse/onebot-11/blob/master/event/notice.md#%E5%A5%BD%E5%8F%8B%E6%B7%BB%E5%8A%A0) 上报格式和onebot格式不匹配.

目前 
{"time":1708963556084,"self_id":robotQQ,"post_type":"request","user_id":QQ,"request_type":"friend","comment":"","flag":"6"}

onebot的格式为
{"time":1708963556084,"self_id":robotQQ,"post_type":"notice","notice_type":"friend_add","user_id":QQ}

**Comment by airdm** [comment]
顺便希望可以支持快速操作.

**Comment by RWdaze** [comment]
这个问题解决了吗？

**Comment by idranme** [comment]
> 这个问题解决了吗？

问题具体在哪？

**Comment by RWdaze** [comment]
> > 这个问题解决了吗？
> 
> 问题具体在哪？
sorry，我这边这个问题不是格式有问题，我的问题是收到好友请求的时候没有收到好友请求上报
只有好友请求的这个消息，我以为这个消息是好友请求
但是确实没有收到好友请求的上报。
![05830f27ce6e57265e915a7af6cd794b](https://github.com/user-attachments/assets/2076efd8-649f-402c-933f-9c34f3af8f68)

**Comment by idranme** [comment]
> > ![05830f27ce6e57265e915a7af6cd794b](https://private-user-images.githubusercontent.com/74894962/399916108-2076efd8-649f-402c-933f-9c34f3af8f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5MTczMzEsIm5iZiI6MTczNTkxNzAzMSwicGF0aCI6Ii83NDg5NDk2Mi8zOTk5MTYxMDgtMjA3NmVmZDgtNjQ5Zi00MDJjLTkzM2YtOWMzNGYzYWY4ZjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDE1MTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YWEwNWMwNTRiMmMzNWIzZjE0MTA0NzllNzNiN2JhMTE3OGViNDBhYjg3ZjcyNzJhNzc1NjQwYTY0YTA1ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kgC6mebaWo7eWyVBi6JV4lLY_iMqcbGxPQoEf9lgI0c)

v4.6.4 是否存在该问题？
