### ISSUE TITLE
没办法收到加群邀请事件

### ISSUE THREAD

**Issue by airdm** [linyuchen/LiteLoaderQQNT-OneBotApi#87]
QQ版本：版本: 9.9.7-21484 (64位)

LLOneBot版本：3.9.0

收不到加群邀请事件的消息.
HTTP POST 收不到 加群邀请的上报
加群请求可以正常收到,但是被邀请的事件没有上报
因为现在机器人加群onebot没有主动加群相关的内容 所以只能靠被动加群,也就是有人邀请机器人加群.这个事件还是挺重要的,希望可以添加.

**Comment by linyuchen** [comment]
[v3.10.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases)已添加
