### ISSUE TITLE
[bug]v3.9.0更新的大部分群管理api无法使用

### ISSUE THREAD

**Issue by xiaole2999** [linyuchen/LiteLoaderQQNT-OneBotApi#89]
QQ版本：
9.9.7-21484
LLOneBot版本：
v3.10.0
调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：
postman、nonebot2
BUG描述：
使用nonebot2框架onebotv11协议和postman直接调用对应接口（如禁言、全体禁言、踢人、设置管理员）显示不支持的api *****（"retcode": 1404）
复现步骤：
按照标准步骤安装，调用接口即可复现
LLOneBot日志:
无日志，api反馈为
{
    "status": "failed",
    "retcode": 1404,
    "data": null,
    "message": "不支持的api set_group_whole_ban",
    "wording": "不支持的api set_group_whole_ban"
}

**Comment by linyuchen** [comment]
无法复现你的情况，调一下`get_version_info`看看版本号，如果版本号是3.9.0，那么把你用postman提交的数据贴出来看一下

**Comment by xiaole2999** [comment]
这个是我自己不仔细，在LiteLoader目录底下有data和plugins两个文件夹，里面都有老版本的llonebot，我以为只要把plugins里的删了就算更新好了，实际上要把data里的也删掉才行，不过我记得我好像没往data里放文件来着（发现个小问题，3.10的manifest version还是3.9）

**Comment by linyuchen** [comment]
> 这个是我自己不仔细，在LiteLoader目录底下有data和plugins两个文件夹，里面都有老版本的llonebot，我以为只要把plugins里的删了就算更新好了，实际上要把data里的也删掉才行，不过我记得我好像没往data里放文件来着（发现个小问题，3.10的manifest version还是3.9）

data里面的不需要删，估计是你放错位置，实际上没有覆盖到原来的

version更正了，重新下载就行

**Comment by xiaole2999** [comment]
> > 这个是我自己不仔细，在LiteLoader目录底下有data和plugins两个文件夹，里面都有老版本的llonebot，我以为只要把plugins里的删了就算更新好了，实际上要把data里的也删掉才行，不过我记得我好像没往data里放文件来着（发现个小问题，3.10的manifest version还是3.9）
> 
> data里面的不需要删，估计是你放错位置，实际上没有覆盖到原来的
> 
> version更正了，重新下载就行

好的，现在已经可以正常使用了
