### ISSUE TITLE
临时会话上报没有sender字段

### ISSUE THREAD

**Issue by MizurenNanako** [linyuchen/LiteLoaderQQNT-OneBotApi#9]
和私聊没有sender是同一个情况（不过现在私聊的已经修复了
临时信息的类型是：`"message_type": "others", "detail_type": "others"`

**Comment by MizurenNanako** [comment]
补充：私聊 和 临时会话 仍然缺少字段 `user_id`

**Comment by MizurenNanako** [comment]
另外，time字段总是为 0 是因为无法获取的缘故吗？

**Comment by linyuchen** [comment]
[v2.1.0](https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi/releases/tag/v2.1.0)已修复，需要更新[LLAPI](https://github.com/linyuchen/LiteLoaderQQNT-Plugin-LLAPI/releases/tag/v1.3.1)
